pipeline:
  test:
    group: test
    image: machines/nuage_build
    pull: true
    environment:
      - GOPATH=/tmp/go
      - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
      - LD_LIBRARY_PATH=/usr/local/lib
      - GO_LDFLAGS_ALLOW='-fopenmp'
    commands:
      # Prepare
      - mkdir -p $GOPATH/src/github.com/mickael-kerjean/nuage
      - mv * $GOPATH/src/github.com/mickael-kerjean/nuage
      - cd $GOPATH/src/github.com/mickael-kerjean/nuage
      - cd server
      - go get
      - go test -v ./...

  publish_docker:
    group: release
    image: docker
    secrets: [ docker_username, docker_password ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: master
    commands:
      - echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin
      - docker pull alpine:latest
      - docker build --no-cache -t machines/nuage:master docker/prod
      - docker push machines/nuage