language: node_js
node_js:
  - "7"

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin

script:
  - npm run image
  - npm run publish

branches:
  only:
  - master
